title: "Power Outage Analysis"
baseurl: "/power-outage-analysis"  # Update with your repo name
url: "https://johnwcollins.github.io"  # Your GitHub Pages URL


remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

